In [2]:
import numpy as np

In [18]:
a = np.array([1,2,3,4,5,6]).reshape(-1,1)
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
a.reshape(-1,2,3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [6]:
b = np.array([1,1,1,1])

In [7]:
a - b

array([0, 1, 2, 3])